### PR TITLE
New data request: police contact deaths

### PR DESCRIPTION
**Pull request by ghost**
# Newly introduced dataset(s):

*deaths-during-or-following-police-contact*

* License: None stated
* Source URL: https://policeconduct.gov.uk/research-and-learning/statistics/annual-deaths-during-or-following-police-contact-statistics

- [x] README files have been created and updated (including listings)
- [ ] We have a license to use any new datasets being added
- [x] CI tests have passed

### CODE REVIEW

**Comment by kimadactyl** [comment]
[License is implied Crown Copyright](https://policeconduct.gov.uk/copyright) as it has not been identified as being the copyright of a third party. Guidance also states "All of the annual death reports are free and available to download from the IOPC website in a PDF format" - we are actually doing them a favour by making it available in an accessible format.

**Comment by kimadactyl** [comment]
Proposed changes:

- [] Add newlines to end of CSV files
- [] Add tests to check that totals add up correctly 
- [] Remove 'total' row
- [] Provide data as a ODS document with multiple worksheets for easy browsing

**Review by kimadactyl — CHANGES_REQUESTED** [review]
Proposed changes:

- [x] Add newlines to end of CSV files
- [x] Add tests to check that totals add up correctly 
- [x] Remove 'total' row
- [x] Provide data as a ODS document with multiple worksheets for easy browsing
- [x] Publish canonical list of forces mentioned in this dataset on README page, ensure they're consistent between outputs

**Comment by ghost** [comment]
I'm not sure the remaining outstanding tasks for this PR make sense

The data has been copy/pasted from the provided ODS file, so there is no scope for errors, and we can't automate tests for the same reason that we can't automate extracting the data - there are multiple tables per sheet.  And we include this ODS file in the source_data directory.

**Comment by kimadactyl** [comment]
OK great then LGTM!

**Pull request merged**
